### ISSUE TITLE
Set up Newrelic and investigate disk usage issues

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#71]
Since release 4.0, we've been having consistently high disk usage on the prod db. ETL was shut down on Sep 15 and brought back up on Sep 18. During this time, EBS byte balance stayed high. This points to the ETL job being the cause of high disk usage. This story is to 

### Acceptance criteria
1. Set up NewRelic on avni-etl so that we can identify these issues
2. Identify and resolve bottlenecks causing high disk usage

![Image](https://github.com/avniproject/avni-etl/assets/344222/be3a39b9-73d4-4697-8ff3-c8cbdf5912db)

**Comment by petmongrels** [comment]
sync telemetry insert seems to be taking a disproportionate amount of time compared to value added by it.

**Comment by vinayvenu** [comment]
Missing index?

**Comment by petmongrels** [comment]
Created the index.
There are no other queries of big concern as of now on ETL. There are few slow ones but they are less frequently run, so not very time consuming. The RDS graph looks better (not sure it is only because of this or if we made other changes as well).



![Image](https://github.com/avniproject/avni-etl/assets/105867/c412619f-26d7-41f8-b5bc-f866da19779e)
